#!/usr/bin/env node

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rootDir = path.resolve(__dirname, "..", "..");
const deploymentsRoot = path.resolve(rootDir, "fhevm-hardhat-template", "deployments");
const abiOutput = path.resolve(__dirname, "..", "abi", "GreenScoreABI.ts");
const addressesOutput = path.resolve(__dirname, "..", "abi", "GreenScoreAddresses.ts");

const KNOWN_CHAIN_IDS = {
  localhost: 31337,
  hardhat: 31337,
  sepolia: 11155111,
};

async function readDeployments() {
  const networks = await fs.readdir(deploymentsRoot).catch(() => []);
  const abiByNetwork = new Map();
  const addresses = {};

  for (const network of networks) {
    const deploymentFile = path.resolve(deploymentsRoot, network, "GreenScore.json");
    try {
      const content = await fs.readFile(deploymentFile, "utf-8");
      const parsed = JSON.parse(content);
      if (!parsed || typeof parsed !== "object") continue;
      if (!Array.isArray(parsed.abi)) continue;
      abiByNetwork.set(network, parsed.abi);

      const resolvedChainId = parsed.chainId ?? parsed.networkId ?? KNOWN_CHAIN_IDS[network] ?? null;
      const entry = {
        address: parsed.address,
        chainId: resolvedChainId,
        chainName: parsed.metadata?.chainName ?? network,
        network,
        transactionHash: parsed.transactionHash ?? undefined,
      };
      addresses[network] = entry;
      if (resolvedChainId) {
        addresses[String(resolvedChainId)] = entry;
      }
    } catch (error) {
      if ((error?.code ?? "") !== "ENOENT") {
        console.warn(`[genabi] skipping ${deploymentFile}:`, error);
      }
    }
  }

  if (!abiByNetwork.size) {
    throw new Error("No GreenScore deployment artifacts found. 确保先运行 hardhat deploy。");
  }

  // Pick the first ABI instance (all network deployments share the same ABI).
  const [abiSample] = abiByNetwork.values();

  return { abi: abiSample, addresses };
}

async function writeAbiFile(abi) {
  const payload = `// Auto-generated by scripts/genabi.mjs. Do not edit.
export const GreenScoreABI = ${JSON.stringify({ abi }, null, 2)} as const;
`;
  await fs.writeFile(abiOutput, payload, "utf-8");
}

async function writeAddressesFile(addresses) {
  const payload = `// Auto-generated by scripts/genabi.mjs. Do not edit.
export const GreenScoreAddresses = ${JSON.stringify(addresses, null, 2)} as const;
`;
  await fs.writeFile(addressesOutput, payload, "utf-8");
}

async function ensureAbiFolder() {
  await fs.mkdir(path.dirname(abiOutput), { recursive: true });
}

async function main() {
  await ensureAbiFolder();
  const { abi, addresses } = await readDeployments();
  await Promise.all([writeAbiFile(abi), writeAddressesFile(addresses)]);
  console.log("[genabi] Updated GreenScore ABI & address book.");
}

main().catch((error) => {
  console.error("[genabi] Generation failed:", error);
  process.exitCode = 1;
});

