// Auto-generated by scripts/genabi.mjs. Do not edit.
export const GreenScoreAddresses = {
  "31337": {
    "address": "0xf82AA47cC1AAD7bdF4acc30bAFa4b40BC4E89F79",
    "chainId": 31337,
    "chainName": "localhost",
    "network": "localhost",
    "transactionHash": "0xf1c9247aecffe7a0bc827441dc3e963af74c702791ab1d9e0e1f58a5a1494b7e"
  },
  "11155111": {
    "address": "0xf82AA47cC1AAD7bdF4acc30bAFa4b40BC4E89F79",
    "chainId": 11155111,
    "chainName": "sepolia",
    "network": "sepolia",
    "transactionHash": "0xc193d678cb34dae631469dd36a8eb1fe4e2bc23d8e7e9e89439c6cca543b4959"
  },
  "localhost": {
    "address": "0xf82AA47cC1AAD7bdF4acc30bAFa4b40BC4E89F79",
    "chainId": 31337,
    "chainName": "localhost",
    "network": "localhost",
    "transactionHash": "0xf1c9247aecffe7a0bc827441dc3e963af74c702791ab1d9e0e1f58a5a1494b7e"
  },
  "sepolia": {
    "address": "0xf82AA47cC1AAD7bdF4acc30bAFa4b40BC4E89F79",
    "chainId": 11155111,
    "chainName": "sepolia",
    "network": "sepolia",
    "transactionHash": "0xc193d678cb34dae631469dd36a8eb1fe4e2bc23d8e7e9e89439c6cca543b4959"
  }
} as const;
